import type { Metadata } from "next";
import { Cairo_Play } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const cairoPlay = Cairo_Play({
  weight: ["400", "500", "600", "700", "800", "900"],
  subsets: ["arabic"],
  display: "swap",
  variable: "--font-cairo-play",
});

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="ar" dir="rtl">
      <body className={`${cairoPlay.variable} antialiased`}>{children}</body>
    </html>
  );
};
